// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types/supabase';
import type { Database } from "@/types/supabase";


const SUPABASE_URL = "https://mawznkkakikkjhwiwmde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hd3pua2tha2lra2pod2l3bWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODMzNTEsImV4cCI6MjA2ODY1OTM1MX0.aEktKcRN-F2v1JhZ55wjMPUieJxY_aZ3-JDpfGVQXu4";

const isBrowser = typeof window !== "undefined";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: isBrowser ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
